@echo off
SET PYTHONPATH=%cd%\library

SET OPENAI_API_KEY=%OPENAI_API_KEY%
SET OPENAI_API_ENDPOINT=%OPENAI_API_ENDPOINT%
SET OPENAI_API_ENGINE=%OPENAI_API_ENGINE%
SET OPENAI_API_VERSION=%OPENAI_API_VERSION%
